### ISSUE TITLE
Setup online documentation with github pages

### ISSUE THREAD

**Issue by tomprogrammer** [tomprogrammer/rust-ascii#10]

**Comment by SimonSapin** [comment]
There are infinite variations to this, but here is how I did it in Kuchiki:

* Go to https://github.com/settings/tokens/new and create a new "personal access token" with only the `repo` "scope". **Warning:** this is like a password that gives push access to all your public repositories. (But it’s revocable.)
* Go to Travis-CI for the relevant repository. Go to "Settings". Under "Environment Variables" add an entry with `TOKEN` as the name, and the hexadecimal string just created from GitHub as the value. Make sure "Display value in build log" is OFF.
* Add something like this https://github.com/SimonSapin/kuchiki/commit/0f89e187e3298b2ad9a7c0a96f9915d00a71be1a to `.travis.yml`, changing `kuchiki` in the `echo …` line to the name of the "main" crate.
* Commit and push to trigger a new build. (Maybe push to a temporary branch where you can freely rewrite commit history until everything is set up right.)

**Comment by tomprogrammer** [comment]
Great, thanks for your short guide! This will definitely save me some time.

**Comment by tomprogrammer** [comment]
Closed in: https://github.com/tomprogrammer/rust-ascii/commit/0d67777478e2fd0c95698d5ea09f4eaec74f0d61
