### ISSUE TITLE
Unsound usages of unsafe implementation from `AsciiStr` to `wider: ty`

### ISSUE THREAD

**Issue by llooFlashooll** [tomprogrammer/rust-ascii#106]
Hi, I am scanning the ascii in the latest version with my own static analyzer tool.

Unsafe conversion found at: src/ascii_str.rs:533:27: 533:62.
``` rust
macro_rules! widen_box {
    ($wider: ty) => {
        #[cfg(feature = "alloc")]
        impl From<Box<AsciiStr>> for Box<$wider> {
            #[inline]
            fn from(owned: Box<AsciiStr>) -> Box<$wider> {
                let ptr = Box::into_raw(owned) as *mut $wider;
                unsafe { Box::from_raw(ptr) }
            }
        }
    };
}
```

This unsound implementation would create a misalignment issues, if the ty is not properly handled like it's other random types.

This would potentially cause [undefined behaviors](https://doc.rust-lang.org/reference/behavior-considered-undefined.html) in Rust. If we further manipulate the problematic converted types, it would potentially lead to different consequences. I am reporting this issue for your attention.

**Comment by tormol** [comment]
The macro is only invoked with `[AsciiChar]`, `[u8]` and `str`, and is not exported.
So I don't think there's any actual "unsound usages".

Is the problem that the macro doesn't check that the type has the same size and alignment as `AsciiStr`?
All the types it's used with are unsized, so `std::mem::align_of::<$wider>()` won't compile, and even if it worked it wouldn't reject `[bool]` which would also be unsound.
I can agree the macro has sharp edges though, and I'll accept a PR replacing `widen_box!` with direct implementations.

**Comment by llooFlashooll** [comment]
Yes, thanks for your reply! Since it's a static analysis, it would be an approximate of all the possibilities. If it's carefully used, there won't be issues.
