### ISSUE TITLE
Moving the repository

### ISSUE THREAD

**Issue by SimonSapin** [tomprogrammer/rust-ascii#11]
I’m not really interested in maintaining this crate. @tomprogrammer, how do you feel about moving it to https://github.com/tomprogrammer/rust-ascii/ ?

**Comment by tomprogrammer** [comment]
That's no problem, I use `rust-ascii` currently and would maintain it in future. There are some issues I want to improve.

Reference #10: Online documentation should be generated after the move, I'm unsure if github redirects gh-pages.

**Comment by SimonSapin** [comment]
Alright, you should have got a request to transfer.

Redirecting gh-pages is not an issue since it’s not set up yet :)
