### ISSUE TITLE
Some feature requests

### ISSUE THREAD

**Issue by osa1** [tomprogrammer/rust-ascii#12]
Thanks for the library. It'd be really awesome if we could add:

* `from_byte(u8) -> Ascii` <- this one is really necessary as there's no way to implement this without exposed `Ascii` constructor.
* `trim(&AsciiStr) -> &AsciiStr` just like String.trim.

If you like the idea I can add these myself and send a pull request.

**Comment by tomprogrammer** [comment]
I published version 0.6.0 of this crate. It includes the functions you requested.

**Comment by osa1** [comment]
That was fast! Thanks!
