### ISSUE TITLE
`no_std` feature is backwards: a `use_std` feature should be used, which is part of the default features

### ISSUE THREAD

**Issue by burtonageo** [tomprogrammer/rust-ascii#29]
Cargo features are supposed to be [additive](https://www.reddit.com/r/rust/comments/37utvn/what_is_the_scope_of_cargos_features/?st=iu8gzbzv&sh=34efee7b), which means the current `no_std` feature is backwards. This is an issue if you're writing a library, because there is currently no way to pass a negative switch (e.g. if I have a `use_std` flag, there is no way to say 'enable the `no_std` flag if it's not enabled.

The current system should be switched, so that there is a `use_std` feature, which is enabled in the default features.

**Comment by tormol** [comment]
Yeah. I learned this a few weeks ago.
When I added the feature I saw other crates do it that way, but thought `no_std` was easier to use.
I wish cargo had a more descriptive way of disabling features than `default-features=false` / --no-default-features.

**Comment by tbu-** [comment]
Fixed by https://github.com/tomprogrammer/rust-ascii/commit/0cf9d8b19bfb58c84ae9a336adfd056e2512a69d.

**Comment by tomprogrammer** [comment]
I'll leave the issue open until I release the new version containing this commit today.

**Comment by cmr** [comment]
@tomprogrammer you still haven't released a new version. please make it 0.8 or something.

**Comment by tomprogrammer** [comment]
I've released version 0.8.0 with all pending changes listed in RELEASES.md.
