### ISSUE TITLE
Implement quickcheck::Arbitrary for AsciiString and AsciiChar

### ISSUE THREAD

**Issue by sid0** [tomprogrammer/rust-ascii#35]
See http://burntsushi.net/rustdoc/quickcheck/trait.Arbitrary.html for a description.

Quickcheck is a randomized testing tool that lets you check general properties. To make your type part of the Quickcheck ecosystem, you need to implement `Arbitrary`, which involves two methods:

(1) generate a random input
(2) shrink a failing input

This should be relatively easy. See http://burntsushi.net/rustdoc/src/quickcheck/arbitrary.rs.html#391 for how it is done for `String` and `char` -- it would probably be straightforward to port that logic to `AsciiString` and `AsciiChar`.

This can be behind a feature gate to make sure that if you aren't using `quickcheck` otherwise, you don't have to pull it in.

(I might do this or get someone else from Facebook to do it -- filing it to keep track :) )

**Comment by tomprogrammer** [comment]
I've implemented this in PR #36. Could you take a quick look? If that's a good enough implementation I will merge it and release a new version.

**Comment by sid0** [comment]
Looks great! Thanks.
