### ISSUE TITLE
Add support for extended ascii

### ISSUE THREAD

**Issue by VitorVRS** [tomprogrammer/rust-ascii#47]
Add characters code from 128 to 255.

**Comment by tormol** [comment]
Then `AsciiStr`/`AsciiString]` would no longer be a binary compatible subtype of `str`/`String`

There are many character sets that extend ASCII, so which one?

**Comment by VitorVRS** [comment]
Good question, idk, but my code is based on LATIN1. 
My issue doesn't make sense now. Sorry.

Btw, `from_ascii_unchecked` solved my problem.
