### ISSUE TITLE
What is the intended behaviour of AsciiStr.lines()?

### ISSUE THREAD

**Issue by tormol** [tomprogrammer/rust-ascii#51]
I assume `"foo\nbar"` producing `["foo"]` is a bug,
But the `lines_iter()` test assert that `AsciiStr::from("\n").lines()` produces nothing, which is not what I expected, and also differs from `str.lines()` (which produces a single empty slice).

`str.lines()` handles `"\r\n"` and trailing newline, so could the (currently rather complex) implementation be replaced with a simple forwarding implementation?

EDIT on 2018-09-11: fixed typo `"foo/nbar"`and corrected `.split()` to `.lines()`.

**Comment by tormol** [comment]
Ping @tomprogrammer.

**Comment by tomprogrammer** [comment]
The implementations in `ascii` should generally behave similar to their couterparts in `std`. Therefore this is a bug.
