### ISSUE TITLE
Publish next version to crate.io?

### ISSUE THREAD

**Issue by tatsuya6502** [tomprogrammer/rust-ascii#62]
Hi. I want to use `AsciiStr::split()`, which is on the [document](https://tomprogrammer.github.io/rust-ascii/ascii/struct.AsciiStr.html#method.split). However, I realized `split` is not in the latest version (0.9.1) of ascii crate published to crates.io.

Can you please publish next version to crate.io if possible?

**Comment by tomprogrammer** [comment]
The version 0.9.2 is released now. Sorry for the long time without activity.
