### ISSUE TITLE
Mark AsciiStr `#[repr(transparent)]` ?

### ISSUE THREAD

**Issue by MaulingMonkey** [tomprogrammer/rust-ascii#65]
I'm unsure if even the non-mut AsciiStr <-> \[AsciiChar\] slice transmutes like this one here are sound, since you generally can't assume that the outer type is compatible with the inner type without using \#[repr(transparent)]:

https://github.com/tomprogrammer/rust-ascii/blob/296c3a827396cd549b32b0714fb8de32ce4452ae/src/ascii_str.rs#L350-L353

**Comment by tormol** [comment]
Good catch! I've added a commit to #63.

**Comment by tormol** [comment]
Released as part of version 1.0.0.
