### ISSUE TITLE
Easy way to get a &str or even just &AsciiStr out of [AsciiChar; _], &[AsciiChar; _] or &[AsciiChar]

### ISSUE THREAD

**Issue by mika-fischer** [tomprogrammer/rust-ascii#76]
I'm a rust beginner, so maybe I'm just doing it wrong. But I can't seem to find a nice way to convert an array or slice of AsciiChar into a str (via &AsciiStr).

The best I could come up with is this, but it still seems overly verbose:
```rust
    let mut s = String::new();
    s.push_str(AsRef::<AsciiStr>::as_ref(&[AsciiChar::A, AsciiChar::B, AsciiChar::C].as_ref()).as_str());
```

**Comment by ryanavella** [comment]
Assuming I understand you correctly, this is possible if you go through `&AsciiStr` first.

```rust
let foo = [AsciiChar::f, AsciiChar::o, AsciiChar::o];
let foo_str = <&AsciiStr>::from(&foo[..]).as_str();
```

**Comment by mika-fischer** [comment]
Much simpler, thanks! 👍
