### ISSUE TITLE
AsciiChar::SOX should be AsciiChar::STX

### ISSUE THREAD

**Issue by chrismooredev** [tomprogrammer/rust-ascii#78]
It seems that this crate's "Start of Text" member (ASCII '\x02') is mislabeled as SOX, whereas everything else on the web (including the linked-to Wikipedia page) references it as STX.

Since this would be a breaking change, I'm not sure how that would fit within the versioning, but I figured I'd report it anyway since I haven't seen any comments for this on the Issues/PRs for this repo.

**Comment by Zenithsiz** [comment]
It should be possible to rename the variant itself and add a deprecated const item to the impl with the previous variant (or just add `STX` as the const item).
Something as such:
```rust
impl AsciiChar {
    #[deprecated("Use `AsciiChar::STX`")]
    pub const SOX: Self = Self::STX;
}
```
This should be technically non-breaking, even in `match` arms, as `AsciiChar` is both `PartialEq` and `Eq`, but not sure if it could break elsewhere.

**Comment by tormol** [comment]
Renaming the variant breaks `use`s, both globs and explicit:
```rust
use ascii::AsciiChar::*; // Warning, unused.
let _ = SOX; // Error, did you mean SO?
```
```rust
use AsciiChar::SOX; // Error, did you mean SOH?
```
I couldn't find much about importing associated constants, other than [a thread saying it's not supported](https://internals.rust-lang.org/t/allow-importing-an-associated-constant-of-a-type/12559) and [another thread explaining why](https://internals.rust-lang.org/t/importing-associated-constants/6610/4). ([the linked reference page](https://doc.rust-lang.org/nightly/reference/items/use-declarations.html#use-declarations) doesn't make it clear at all).

I'll deprecate the variant, and then maybe rename with associated constant as fallback in a later version.

On the other hand I doubt which way it's done matters,  
as I assume the only reason to glob-import will be to create a hardcoded `&AsciiStr` from `&[AsciiChar]` with printable characters. And `use`ing select characters seems rather pointless.
