### ISSUE TITLE
Publish new version with the alloc feature?

### ISSUE THREAD

**Issue by stuffmatic** [tomprogrammer/rust-ascii#79]
I'm using this crate in a `no_std` environment by enabling the [alloc feature](https://github.com/tomprogrammer/rust-ascii/commit/1a910338f4549cf631f163f161559da0d0ad7d11) as [described in the readme](https://github.com/tomprogrammer/rust-ascii#using-ascii-without-libstd). However, this feature is not included in the 1.0.0 version as the readme seems to imply, so maybe it would be good to publish a new version that includes the alloc feature and any other recent additions?

**Comment by ibraheemdev** [comment]
https://github.com/tomprogrammer/rust-ascii/commit/e888608c070bcf85706a65db4e29941a49bfd84e also fixed a soundness issue in `str as AsMutAsciiStr` that has not been released, cc @tomprogrammer.

**Comment by xkr47** [comment]
It seems @tomprogrammer has not had any activity on github whatsoever since Decmber 2020. Would somebody be interested in maintaining a fork?

**Comment by tormol** [comment]
I just realized I can merge stuff, so I'll go though the open PRs (and fix my own :smile:).
I can't release on crates.io though, but @tbu- and @SimonSapin can.

**Comment by tomprogrammer** [comment]
Hi, I didn't care about this crate for too long time, sorry. I will help to get out a new release. After that I think it would be good to distribute maintenance of the crate further.

**Comment by tormol** [comment]
I have a release commit ready (#90), but can't publish to crates.io.
@tomprogrammer can you add me as owner?

**Comment by tormol** [comment]
Thanks @tomprogrammer.
Version 1.1 is now released!
