### ISSUE TITLE
Complete the set of traits that string types implement

### ISSUE THREAD

**Issue by tomprogrammer** [tomprogrammer/rust-ascii#8]
From the documentation of `std::string::String` following traits could/should be implemented for ascii strings:
- [x] `FromIterator`
- [x] `Extend`
- [ ] `Pattern` (tracked in #53)
- [x] `Default`
- [x] `Add`
- [x] `Index` (both `AsciiString` and `AsciiStr`)
- [x] `Write` (PR #33)
- [x] More inherent methods on `AsciiString`

**Comment by tomprogrammer** [comment]
There is some work in progress in branch [feat-impl-more-traits](https://github.com/SimonSapin/rust-ascii/tree/feat-impl-more-traits).

**Comment by tormol** [comment]
String doesn't implement `Write`, and implementing `Pattern` is unstable.

Are you waiting for `Pattern` to become stable?

**Comment by tomprogrammer** [comment]
I've meant `std::fmt::Write` which is now implemented in the contributed PR #33. I will have to check how to proceed with `Pattern` since it's unstable right now.

**Comment by tomprogrammer** [comment]
The `Pattern` trait will be tracked in #53.
